### PR TITLE
feat: select shipping address

### PR DESCRIPTION
**Pull request by ddanielsantos**

### CODE REVIEW

**Review by daniloab — COMMENTED** [review]
add the prettier to run in your pre commit

**Comment by daniloab** [comment]
print?

**Comment by ddanielsantos** [comment]
@daniloab [pre-commit](https://github.com/ddanielsantos/rust-commerce/blob/main/.husky/pre-commit#L5) script was already added

**Comment by ddanielsantos** [comment]
I only added another select + modal, i'm styling them now and will submit in a new PR
shipping

**Pull request merged**
